// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGhHR6mPL4jPEiE69K93_4GOljTepsykk',
    appId: '1:567604890045:web:4496ec786987cca8226ad4',
    messagingSenderId: '567604890045',
    projectId: 'banter-f1893',
    authDomain: 'banter-f1893.firebaseapp.com',
    storageBucket: 'banter-f1893.appspot.com',
    measurementId: 'G-J6KW8T79EX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWdk7GIq18Iw27oR_i8Zx_MsuYXVmDQ8I',
    appId: '1:567604890045:android:b67970a259c32de9226ad4',
    messagingSenderId: '567604890045',
    projectId: 'banter-f1893',
    storageBucket: 'banter-f1893.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHEQWp7s820IXxLt_8by7AFCOzlX6Q0MA',
    appId: '1:567604890045:ios:1b838476da3816e7226ad4',
    messagingSenderId: '567604890045',
    projectId: 'banter-f1893',
    storageBucket: 'banter-f1893.appspot.com',
    iosBundleId: 'com.example.banter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHEQWp7s820IXxLt_8by7AFCOzlX6Q0MA',
    appId: '1:567604890045:ios:1b838476da3816e7226ad4',
    messagingSenderId: '567604890045',
    projectId: 'banter-f1893',
    storageBucket: 'banter-f1893.appspot.com',
    iosBundleId: 'com.example.banter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGhHR6mPL4jPEiE69K93_4GOljTepsykk',
    appId: '1:567604890045:web:ecaef95854bc4214226ad4',
    messagingSenderId: '567604890045',
    projectId: 'banter-f1893',
    authDomain: 'banter-f1893.firebaseapp.com',
    storageBucket: 'banter-f1893.appspot.com',
    measurementId: 'G-47BX5ZD2CC',
  );
}
